version: "2"
services:
      nodejs:
            build: ./nodejs
            ports:
                - 5000:5000
            depends_on:
                - mysql
            command: 'node /src/server.js'
      php:
            build: ./build/php
            volumes:
              - ./src:/var/www/html
            links:
              - mysql
      mysql:
            image: mysql:5.7
            container_name: mysql
            volumes:
              - ./build/mysql:/docker-entrypoint-initdb.d
              - ./tmp/mysql:/var/lib/mysql
            environment:
              - MYSQL_DATABASE=ask
              - MYSQL_ROOT_PASSWORD=ask
      pma:
            image: phpmyadmin/phpmyadmin
            links:
              - mysql:db
            ports:
              - 8080:80
